// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./src/components/Brother/A.vue')['default']
    Axios: typeof import('./src/components/Axios/index.vue')['default']
    B: typeof import('./src/components/Brother/B.vue')['default']
    Brother: typeof import('./src/components/Brother/index.vue')['default']
    C: typeof import('./src/components/DynamicComponents/C.vue')['default']
    DynamicComponents: typeof import('./src/components/DynamicComponents/index.vue')['default']
    DynamicCss: typeof import('./src/components/DynamicCss/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElementUI: typeof import('./src/components/ElementUI/index.vue')['default']
    Father: typeof import('./src/components/FatherAndSon/Father.vue')['default']
    JsStyle: typeof import('./src/components/DynamicCss/jsStyle.vue')['default']
    Pinia: typeof import('./src/components/Pinia/index.vue')['default']
    'Provide&Inject': typeof import('./src/components/Provide&Inject/index.vue')['default']
    Router: typeof import('./src/components/Router/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/Suspense/Skeleton.vue')['default']
    Slot: typeof import('./src/components/Slot/index.vue')['default']
    Son: typeof import('./src/components/FatherAndSon/Son.vue')['default']
    Suspense: typeof import('./src/components/Suspense/index.vue')['default']
    'ToRef&ToRefs': typeof import('./src/components/ToRef&ToRefs/index.vue')['default']
  }
}
