name: vueApp upload to Tencent cloud # 工作流名称

on:
  push:
    branches: "master" # 当 master 分支发生改变时触发工作流

jobs:
  dockerActions:
    runs-on: ubuntu-latest # 指定工作流运行的系统

    steps:
      - name: checkout code # 拉取代码
        uses: actions/checkout@v3

      - name: build docker image # 打包 docker 镜像
        run: docker build -t ${{ secrets.DOCKER_IMAGE }} .

      - name: Login to Tencent cloud container image service # 登录腾讯云容器镜像服务
        run: docker login ccr.ccs.tencentyun.com --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: build Tencent cloud container image tag # 将镜像进行构建并打包成 腾讯云镜像 tag
        run: docker tag ${{ secrets.DOCKER_IMAGE }} ccr.ccs.tencentyun.com/my-mxc-docker/vueapp-docker-image:${{ secrets.DOCKER_IMAGE_TAG }}

      - name: push docker image # 推送 docker 镜像
        run: docker push ccr.ccs.tencentyun.com/my-mxc-docker/vueapp-docker-image:${{ secrets.DOCKER_IMAGE_TAG }}

  deployDockerImage:
    needs: dockerActions # 等待 dockerActions 执行完毕
    runs-on: ubuntu-latest # 指定工作流运行的系统

    steps:
      - name: Login to Tencent cloud server # 登录腾讯云服务器
        uses: appleboy/ssh-action@master # 这里从 easingthemes/ssh-deploy@v2.2.11 换成了 appleboy/ssh-action@master
        with:
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          host:  ${{ secrets.REMOTE_HOST }}
          script: |
            # 停止旧版容器
            docker stop ${{ secrets.DOCKER_CONTAINER }}

            # 删除旧版容器
            docker rm ${{ secrets.DOCKER_CONTAINER }}

            # 删除旧版镜像
            docker rmi ccr.ccs.tencentyun.com/my-mxc-docker/vueapp-docker-image:${{ secrets.DOCKER_IMAGE_TAG }}

            # 登录腾讯云容器镜像服务
            docker login ccr.ccs.tencentyun.com --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
            
            # 拉取镜像
            docker pull ccr.ccs.tencentyun.com/my-mxc-docker/vueapp-docker-image:${{ secrets.DOCKER_IMAGE_TAG }}

            # 运行镜像
            docker run -d -p 8000:80 --name ${{ secrets.DOCKER_CONTAINER }} ccr.ccs.tencentyun.com/my-mxc-docker/vueapp-docker-image:${{ secrets.DOCKER_IMAGE_TAG }}
