name: 打包应用并上传到云服务器

on:
  push:
    branches: 'master'

jobs:
  cache-and-install:
    # 任务运行所需要的虚拟机环境(必填)
    runs-on: ubuntu-latest

    steps:
      - name: 拉取源码
        uses: actions/checkout@v3

      - name: 安装 node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.9.0

      - name: 设置 pnpm 缓存(优化部署速度)
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: 安装 cache 优化 pnpm 缓存(优化部署速度)
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 安装依赖
        run: pnpm install

      - name: 打包
        run: pnpm run build

      - name: 发布到云服务器
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: 'http'
          TARGET: '/www/wwwroot/'
          ARGS: '-avzr --delete'
